# Generated by Django 5.2.1 on 2025-05-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clientes', '0001_initial'),
        ('gestion_propiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Etapa')),
                ('alias_etapa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias Etapa')),
                ('descripcion_etapa', models.TextField(blank=True, null=True, verbose_name='Descripcion Etapa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'etapas',
                'ordering': ['id_etapa'],
            },
        ),
        migrations.CreateModel(
            name='CampoEtapa',
            fields=[
                ('id_campo_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Campo')),
                ('tipo_dato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Datos')),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('descripcion_campo', models.TextField(blank=True, max_length=50, null=True, verbose_name='Descripcion Campo')),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escrituracion.etapas')),
            ],
            options={
                'verbose_name': 'Campo Etapa',
                'verbose_name_plural': 'Campos Etapas',
                'db_table': 'campo_etapas',
                'ordering': ['id_etapa'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now=True)),
                ('estado_venta', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Desistida', 'Desistida'), ('Otro_1', 'Otro_1'), ('Otro_2', 'Otro_2')], default='Activa', max_length=50, verbose_name='Estado Venta')),
                ('fecha_promesa', models.DateField(verbose_name='Fecha de promesa')),
                ('ejecutivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ejecutivo')),
                ('bono_pie', models.FloatField(blank=True, null=True, verbose_name='Bon Pie')),
                ('uf_por_m2', models.FloatField(blank=True, null=True, verbose_name='UF Por M2')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.cliente')),
                ('id_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.propiedade')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaEtapa',
            fields=[
                ('id_venta_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('motivo_compra', models.TextField(blank=True, null=True, verbose_name='Motivo Compra')),
                ('atributos', models.TextField(blank=True, null=True, verbose_name='Atributos')),
                ('ggoo', models.IntegerField(blank=True, null=True, verbose_name='Gastos Operacionales')),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escrituracion.etapas')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escrituracion.venta')),
            ],
            options={
                'verbose_name': 'Venta Etapa',
                'verbose_name_plural': 'Ventas Etapas',
                'db_table': 'venta_etapas',
                'ordering': ['id_venta_etapa'],
            },
        ),
        migrations.CreateModel(
            name='ValoresEtapa',
            fields=[
                ('id_valores_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('valor_campo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Campo')),
                ('id_campo_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escrituracion.campoetapa')),
                ('id_venta_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escrituracion.ventaetapa')),
            ],
            options={
                'verbose_name': 'Valor Etapa',
                'verbose_name_plural': 'Valores Etapas',
                'db_table': 'valores_etapas',
                'ordering': ['id_valores_etapa'],
            },
        ),
    ]
