# Generated by Django 5.2.1 on 2025-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaetapa',
            name='atributos',
        ),
        migrations.RemoveField(
            model_name='ventaetapa',
            name='ggoo',
        ),
        migrations.RemoveField(
            model_name='ventaetapa',
            name='motivo_compra',
        ),
        migrations.AddField(
            model_name='venta',
            name='atributos',
            field=models.TextField(blank=True, null=True, verbose_name='Atributos'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ggoo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gastos Operacionales'),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_compra',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo Compra'),
        ),
    ]
