# Generated by Django 5.2.1 on 2025-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0002_remove_ventaetapa_atributos_remove_ventaetapa_ggoo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Contado', 'Contado')], default='Activa', max_length=50, verbose_name='Tipo de venta'),
        ),
    ]
