# Generated by Django 5.2.1 on 2025-05-19 17:18

import gestion_escrituracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0003_venta_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='aplicacion_bono',
            field=models.CharField(choices=[('No Aplica', 'No Aplica'), ('Precio', 'Precio'), ('Pie', 'Pie')], default='No Aplica', max_length=10, verbose_name='Aplicación Bono'),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_campagna',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Dcsto X Campaña'),
        ),
        migrations.AddField(
            model_name='venta',
            name='uf_descuento_campagna',
            field=models.FloatField(default=1, help_text='Campaña dscto', validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Dcts Cam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='bono_pie',
            field=models.FloatField(blank=True, null=True, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Bon Pie'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Desistida', 'Desistida'), ('Otro_1', 'Otro_1'), ('Otro_2', 'Otro_2')], default='Activa', help_text='Estado Vent', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ggoo',
            field=models.IntegerField(blank=True, help_text='Gastos Operacionales', null=True, verbose_name='GGOO'),
        ),
    ]
