# Generated by Django 5.2.1 on 2025-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0004_venta_aplicacion_bono_venta_descuento_campagna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_promesa',
            field=models.DateField(help_text='Fecha de promesa', verbose_name='F.Promesa'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now=True, help_text='Fecha de Venta', verbose_name='F.Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Contado', 'Contado')], default='Activa', help_text='Tipo de venta', max_length=50, verbose_name='Tipo'),
        ),
    ]
