# Generated by Django 5.2.1 on 2025-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0005_alter_venta_fecha_promesa_alter_venta_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio_venta',
            field=models.FloatField(default=0, help_text='Precio venta', verbose_name='P.Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento_campagna',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Dcto Camp'),
        ),
    ]
