# Generated by Django 5.2.1 on 2025-05-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0006_venta_precio_venta_alter_venta_descuento_campagna'),
        ('gestion_propiedad', '0006_alter_propiedade_estado_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapas',
            name='tipo_venta_asociado',
            field=models.CharField(blank=True, choices=[('Credito', 'Credito'), ('Contado', 'Contado')], help_text='Tipo de venta al que pertenece esta etapa', max_length=50, null=True, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_propiedad',
            field=models.ForeignKey(limit_choices_to={'estado_propiedad': 'Libre'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.propiedade'),
        ),
    ]
