# Generated by Django 5.2.1 on 2025-05-23 19:42

import gestion_escrituracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0007_etapas_tipo_venta_asociado_alter_venta_id_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='credito_hipotecario',
            field=models.FloatField(blank=True, null=True, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Credito Hipotecario'),
        ),
    ]
