# Generated by Django 5.2.1 on 2025-05-27 13:50

import gestion_escrituracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0008_venta_credito_hipotecario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='saldo_contado',
            field=models.FloatField(blank=True, null=True, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Saldo Contado'),
        ),
        migrations.AlterField(
            model_name='etapas',
            name='tipo_venta_asociado',
            field=models.CharField(blank=True, choices=[('Credito', 'Crédito'), ('Contado', 'Contado')], help_text='Tipo de venta al que pertenece esta etapa', max_length=50, null=True, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Credito', 'Crédito'), ('Contado', 'Contado')], default='Activa', help_text='Tipo de venta', max_length=50, verbose_name='Tipo'),
        ),
    ]
