# Generated by Django 5.2.1 on 2025-05-27 15:52

import gestion_escrituracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0009_venta_saldo_contado_alter_etapas_tipo_venta_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='recursos_propio',
            field=models.FloatField(blank=True, null=True, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Recursos Propios'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subsidio',
            field=models.FloatField(blank=True, null=True, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Subsidio'),
        ),
    ]
