# Generated by Django 5.2.1 on 2026-08-17 15:26

import gestion_escrituracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0010_venta_recursos_propio_venta_subsidio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='bono_pie',
            field=models.FloatField(default=0, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Bon Pie'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='credito_hipotecario',
            field=models.FloatField(default=0, validators=[gestion_escrituracion.models.validar_positivo], verbose_name='Credito Hipotecario'),
        ),
    ]
