# Generated by Django 5.2.1 on 2026-10-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0011_alter_venta_bono_pie_alter_venta_credito_hipotecario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Desistida', 'Desistida'), ('Promesa', 'Promesa'), ('Reserva', 'Reserva')], default='Activa', help_text='Estado Vent', max_length=50, verbose_name='Estado'),
        ),
    ]
