# Generated by Django 5.2.1 on 2026-10-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0012_alter_venta_estado_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now_add=True, help_text='Fecha de Venta', verbose_name='F.Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Credito', 'Crédito'), ('Contado', 'Contado')], default='Credito', help_text='Tipo de venta', max_length=50, verbose_name='Tipo'),
        ),
    ]
