# Generated by Django 5.2.1 on 2026-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0013_alter_venta_fecha_venta_alter_venta_tipo_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campoetapa',
            name='tipo_dato',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Fecha', 'Fecha'), ('Numero', 'Número'), ('Monto', 'Monto'), ('SiNo', 'Sí / No'), ('TextoLargo', 'Texto largo')], default='Texto', max_length=20, verbose_name='Tipo de dato'),
        ),
    ]
