# Generated by Django 5.2.1 on 2026-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escrituracion', '0014_alter_campoetapa_tipo_dato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresetapa',
            name='valor_campo',
            field=models.TextField(blank=True, null=True, verbose_name='Valor'),
        ),
    ]
