# Generated by Django 5.2.1 on 2025-05-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProfesion',
            fields=[
                ('id_area_profesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area_profesion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Area de Profesion',
                'verbose_name_plural': 'Areas de Profesion',
                'db_table': 'area_profesion',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nacionalidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Nacionalidade',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'nacionalidade',
            },
        ),
        migrations.CreateModel(
            name='Profesione',
            fields=[
                ('id_profesione', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_profesione', models.CharField(max_length=100)),
                ('id_area_profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.areaprofesion')),
            ],
            options={
                'verbose_name': 'Profesione',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'profesione',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(choices=[('Natural', 'Natural'), ('Empresa', 'Empresa')], default='Natural', max_length=50)),
                ('rut_cliente', models.CharField(max_length=50, verbose_name='Rut Cliente')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Sin Definir', 'Sin Definir'), ('Otro', 'Otro')], default='Sin Definir', max_length=30, verbose_name='Género')),
                ('region', models.CharField(choices=[('I REGIÓN DE TARAPACÁ', 'I REGIÓN DE TARAPACÁ'), ('II REGIÓN DE ANTOFAGASTA', 'II REGIÓN DE ANTOFAGASTA'), ('III REGIÓN DE ATACAMA', 'III REGIÓN DE ATACAMA'), ('IV REGIÓN DE COQUIMBO', 'IV REGIÓN DE COQUIMBO'), ('V REGIÓN DE VALPARAÍSO', 'V REGIÓN DE VALPARAÍSO'), ('VI REGIÓN DE O´HIGGINS', 'VI REGIÓN DE O´HIGGINS'), ('VII REGIÓN DEL MAULE', 'VII REGIÓN DEL MAULE'), ('XVI REGIÓN DEL ÑUBLE', 'XVI REGIÓN DEL ÑUBLE'), ('VIII REGIÓN DEL BÍO-BÍO', 'VIII REGIÓN DEL BÍO-BÍO'), ('IX REGIÓN DE LA ARAUCANÍA', 'IX REGIÓN DE LA ARAUCANÍA'), ('X REGIÓN DE LOS LAGOS', 'X REGIÓN DE LOS LAGOS'), ('XI REGIÓN DE AYSÉN', 'XI REGIÓN DE AYSÉN'), ('XII REGIÓN DE MAGALLANES', 'XII REGIÓN DE MAGALLANES'), ('REGIÓN METROPOLITANA', 'REGIÓN METROPOLITANA'), ('XIV DE LOS RÍOS', 'XIV DE LOS RÍOS'), ('XV REGIÓN DE ARICA Y PARINACOTA', 'XV REGIÓN DE ARICA Y PARINACOTA')], default='IV REGIÓN DE COQUIMBO', max_length=31, verbose_name='Región')),
                ('nombres_cliente', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos_cliente', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('renta', models.IntegerField(verbose_name='Renta')),
                ('id_nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.nacionalidade', verbose_name='Nacionalidad')),
                ('id_profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_clientes.profesione', verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['id_cliente'],
            },
        ),
    ]
