# Generated by Django 5.2.1 on 2025-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos_1',
            field=models.CharField(default='Alvarez', max_length=50, verbose_name='1er Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos_2',
            field=models.CharField(default='Alvarez', max_length=50, verbose_name='2do Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres_1',
            field=models.CharField(default='Luis', max_length=50, verbose_name='1er Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres_2',
            field=models.CharField(default='Alberto', max_length=50, verbose_name='2do Nombre'),
            preserve_default=False,
        ),
    ]
