# Generated by Django 5.2.1 on 2026-10-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_remove_cliente_apellidos_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_educacional',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nivel educacional'),
        ),
    ]
