# Generated by Django 5.2.1 on 2026-10-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0003_cliente_ciudad_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a')], default='', max_length=30, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nivel_educacional',
            field=models.CharField(blank=True, choices=[('Enseñanza Básica', 'Enseñanza Básica'), ('Enseñanza Media', 'Enseñanza Media'), ('Técnico Profesional', 'Técnico Profesional'), ('Técnico Nivel Superior', 'Técnico Nivel Superior'), ('Profesional', 'Profesional')], default='', max_length=100, verbose_name='Nivel educacional'),
        ),
    ]
