# Generated by Django 5.2.1 on 2025-05-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_escrituracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=50, verbose_name='Nombre Banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
                'ordering': ['nombre_banco'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaPago',
            fields=[
                ('id_categoria_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_pago', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
            options={
                'verbose_name': 'Categoria Pago',
                'verbose_name_plural': 'Categorias Pagos',
                'db_table': 'categoria_pago',
                'ordering': ['id_categoria_pago'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_forma_pago', models.CharField(max_length=50, verbose_name='Nombre Forma')),
            ],
            options={
                'verbose_name': 'Forma Pago',
                'verbose_name_plural': 'Formas Pagos',
                'db_table': 'forma_pago',
                'ordering': ['id_forma_pago'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Contabilizado', 'Contabilizado')], default='Pendiente', max_length=50, verbose_name='Estado Pago')),
                ('num_documento', models.CharField(max_length=50, verbose_name='Numero de Documento')),
                ('fecha_registro_pago', models.DateField(verbose_name='Fecha de registro')),
                ('fecha_real_pago', models.DateField(verbose_name='Fecha contable')),
                ('monto_pago', models.IntegerField(verbose_name='Monto de pago')),
                ('observacion_pago', models.CharField(max_length=100, verbose_name='Observaciones de pago')),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_contable.bancos')),
                ('id_categoria_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_contable.categoriapago')),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_contable.formapago')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_escrituracion.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['id_pago'],
            },
        ),
    ]
