# Generated by Django 5.2.1 on 2025-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorUf',
            fields=[
                ('id_valor_uf', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('valor_uf', models.FloatField(verbose_name='Valor de UF')),
            ],
            options={
                'verbose_name': 'Valor de UF',
                'verbose_name_plural': 'Valores de UF',
                'db_table': 'valor_uf',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
