# Generated by Django 5.2.1 on 2025-05-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contable', '0002_valoruf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='uf_pago',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto en UF'),
        ),
    ]
