# Generated by Django 5.2.1 on 2026-10-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_contable', '0003_pagos_uf_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoruf',
            name='fecha_registro',
            field=models.DateField(unique=True, verbose_name='Fecha de registro'),
        ),
    ]
