# Generated by Django 5.2.1 on 2025-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razon Social')),
                ('rut_empresa', models.CharField(max_length=50, verbose_name='Rut Empresa')),
                ('gerente_ventas', models.CharField(max_length=50, verbose_name='Gerente Ventas')),
                ('jefe_operaciones', models.CharField(max_length=50, verbose_name='Jefes Operaciones')),
                ('banco_alzante', models.CharField(max_length=50, verbose_name='Banco Alzante')),
                ('notaria', models.CharField(max_length=50, verbose_name='Notaria')),
                ('banco_transf', models.CharField(max_length=50, verbose_name='Banco Transferencia')),
                ('tipo_cuenta_transf', models.CharField(max_length=50, verbose_name='Tipo de Cuenta')),
                ('num_cuenta_transf', models.CharField(max_length=50, verbose_name='No Cuenta')),
                ('correo_transf', models.CharField(max_length=50, verbose_name='Correo Transferencia')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
    ]
