# Generated by Django 5.2.1 on 2025-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='representante',
            field=models.CharField(default='Sebastian Rodrigo Araya Varela', max_length=50, verbose_name='Representante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='rut_representante',
            field=models.CharField(default='11.610.180-7', max_length=50, verbose_name='Rut Representante'),
            preserve_default=False,
        ),
    ]
