# Generated by Django 5.2.1 on 2025-05-16 21:56

import django.db.models.deletion
import gestion_propiedad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id_condominio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_condominio', models.CharField(max_length=100, verbose_name='Nombre')),
                ('alias_condominio', models.CharField(max_length=50, verbose_name='Alias Condominio')),
                ('fecha_venta_condominio', models.DateField(blank=True, null=True, verbose_name='Fecha Venta Condominio')),
                ('direccion_proyecto', models.CharField(max_length=100, verbose_name='Dirección')),
                ('estado_condominio', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'db_table': 'condominio',
                'ordering': ['id_condominio'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=4, verbose_name='Nombre')),
                ('programa_modelo', models.CharField(max_length=10, verbose_name='Programa')),
                ('estado_modelo', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'db_table': 'modelo',
                'ordering': ['id_modelo'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa_condominio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(max_length=50, verbose_name='Nombre')),
                ('id_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.condominio', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Condominios',
                'db_table': 'etapa_proyecto',
                'ordering': ['id_etapa_condominio'],
            },
        ),
        migrations.CreateModel(
            name='Propiedade',
            fields=[
                ('id_propiedad', models.AutoField(primary_key=True, serialize=False)),
                ('estado_propiedad', models.CharField(choices=[('Libre', 'Libre'), ('Tomada', 'Tomada')], default='Libre', max_length=50, verbose_name='Estado Propiedad')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol Propiedad')),
                ('numero_propiedad', models.CharField(max_length=3, verbose_name='Número Propiedad')),
                ('ori_vivienda', models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('ORIENTE', 'ORIENTE'), ('PONIENTE', 'PONIENTE'), ('NOR ORIENTE', 'NOR ORIENTE'), ('SUR PONIENTE', 'SUR PONIENTE'), ('NOR PONIENTE', 'NOR PONIENTE'), ('SUR ORIENTE', 'SUR ORIENTE')], default='Norte', max_length=30, verbose_name='Orientación')),
                ('estado_vivienda', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30, verbose_name='Estado vivienda')),
                ('piso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=30, verbose_name='Piso')),
                ('metros_vivienda', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Metros depto')),
                ('metros_terraza_vivienda', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Metros terraza')),
                ('metros_total_vivienda', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Metros total')),
                ('bono_vivienda', models.FloatField(blank=True, null=True, verbose_name='% Descuento')),
                ('prorrateo_vivienda', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='% Prorrateo')),
                ('estacionamiento', models.CharField(max_length=5, verbose_name='Estacionamiento')),
                ('bodega', models.CharField(max_length=5, verbose_name='Bodega')),
                ('m2_bodega', models.CharField(max_length=5, verbose_name='M2 Bodega')),
                ('valor_inicial_vivienda', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Valor Inicial')),
                ('valor_inicial_final', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Valor Final')),
                ('valor_cchc', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Precio CCHC')),
                ('campagna_dscto', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='Campaña dscto')),
                ('valor_dscto', models.FloatField(validators=[gestion_propiedad.models.validar_positivo], verbose_name='UF Dscto')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.condominio', verbose_name='Condominio')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.etapa', verbose_name='Etapa')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'propiedades',
                'ordering': ['id_propiedad'],
            },
        ),
        migrations.CreateModel(
            name='SubEtapa',
            fields=[
                ('id_sub_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sub_etapa', models.CharField(max_length=4, verbose_name='Nombre Sub Etapa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Condominios',
                'db_table': 'sub_etapa_proyecto',
                'ordering': ['id_sub_etapa'],
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id_torre', models.AutoField(primary_key=True, serialize=False)),
                ('estado_torre', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=30, verbose_name='Estado')),
                ('nombre_torre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('id_etapa_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.etapa', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'db_table': 'torre',
                'ordering': ['id_torre'],
            },
        ),
    ]
