# Generated by Django 5.2.1 on 2025-05-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['id_etapa_condominio'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['id_modelo'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelOptions(
            name='subetapa',
            options={'ordering': ['id_sub_etapa'], 'verbose_name': 'Sub Etapa', 'verbose_name_plural': 'Sub Etapas'},
        ),
    ]
