# Generated by Django 5.2.1 on 2025-05-19 14:51

import django.db.models.deletion
import gestion_propiedad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0002_alter_etapa_options_alter_modelo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedade',
            name='bono_vivienda',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='estado_vivienda',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='metros_terraza_vivienda',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='metros_total_vivienda',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='ori_vivienda',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='prorrateo_vivienda',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='valor_inicial_final',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='valor_inicial_vivienda',
        ),
        migrations.AddField(
            model_name='propiedade',
            name='bono_propiedad',
            field=models.FloatField(blank=True, help_text='Descuento Depto', null=True, verbose_name='% Dcts'),
        ),
        migrations.AddField(
            model_name='propiedade',
            name='metros_terraza_propiedad',
            field=models.FloatField(default=1, help_text='Metros^2 Terraza', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Mtrs Trr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='metros_total_propiedad',
            field=models.FloatField(default=1, help_text='Metros^2 Total', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Mtrs TT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='ori_propiedad',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('ORIENTE', 'ORIENTE'), ('PONIENTE', 'PONIENTE'), ('NOR ORIENTE', 'NOR ORIENTE'), ('SUR PONIENTE', 'SUR PONIENTE'), ('NOR PONIENTE', 'NOR PONIENTE'), ('SUR ORIENTE', 'SUR ORIENTE')], default='Norte', help_text='Orientación Depto', max_length=30, verbose_name='Ori'),
        ),
        migrations.AddField(
            model_name='propiedade',
            name='prorrateo_propiedad',
            field=models.FloatField(default=1, help_text='% Prorrateo', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Prrt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='valor_final_propiedad',
            field=models.FloatField(default=1, help_text='Precio Final', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Precio F'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='valor_inicial_propiedad',
            field=models.FloatField(default=1, help_text='Precio Incial', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Precio I'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='bodega',
            field=models.CharField(help_text='N° Bodega', max_length=5, verbose_name='Bdg'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='campagna_dscto',
            field=models.FloatField(help_text='Campaña dscto', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Dcts Cam'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='condominio',
            field=models.ForeignKey(help_text='Nombre del Condominio', on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.condominio', verbose_name='Condominio'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='estacionamiento',
            field=models.CharField(help_text='N° Estacionamiento', max_length=5, verbose_name='Est'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='estado_propiedad',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Tomada', 'Tomada')], default='Libre', help_text='Estado Propiedad', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='etapa',
            field=models.ForeignKey(help_text='Etapa del proyecto', on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.etapa', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='m2_bodega',
            field=models.CharField(help_text='Metros^2 Bodega', max_length=5, verbose_name='M^2 Bdg'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='metros_vivienda',
            field=models.FloatField(help_text='Metros^2 Depto', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Mtrs'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='modelo',
            field=models.ForeignKey(help_text='Modelo Depto', on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='numero_propiedad',
            field=models.CharField(help_text='N° Depto', max_length=3, verbose_name='N°'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='rol',
            field=models.CharField(help_text='Rol Propiedad', max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_cchc',
            field=models.FloatField(help_text='recio CCHC', validators=[gestion_propiedad.models.validar_positivo], verbose_name='P$.CCHC'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_dscto',
            field=models.FloatField(help_text='UF Descuento', validators=[gestion_propiedad.models.validar_positivo], verbose_name='UF Dcts'),
        ),
    ]
