# Generated by Django 5.2.1 on 2025-05-19 17:18

import gestion_propiedad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0003_remove_propiedade_bono_vivienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedade',
            name='campagna_dscto',
        ),
        migrations.RemoveField(
            model_name='propiedade',
            name='valor_dscto',
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_final_propiedad',
            field=models.FloatField(help_text='Precio Final', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Precio Fin'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_inicial_propiedad',
            field=models.FloatField(help_text='Precio Incial', validators=[gestion_propiedad.models.validar_positivo], verbose_name='Precio Ini'),
        ),
    ]
