# Generated by Django 5.2.1 on 2025-05-20 16:23

import gestion_propiedad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0004_remove_propiedade_campagna_dscto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedade',
            name='valor_cchc',
            field=models.FloatField(blank=True, help_text='recio CCHC', null=True, validators=[gestion_propiedad.models.validar_positivo], verbose_name='P$.CCHC'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_final_propiedad',
            field=models.FloatField(blank=True, help_text='Precio Final', null=True, verbose_name='Precio Fin'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_inicial_propiedad',
            field=models.FloatField(blank=True, help_text='Precio Incial', null=True, verbose_name='Precio Ini'),
        ),
    ]
