# Generated by Django 5.2.1 on 2025-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0005_alter_propiedade_valor_cchc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedade',
            name='estado_propiedad',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Tomada', 'Tomada'), ('Entregada', 'Entregada')], default='Libre', help_text='Estado Propiedad', max_length=50, verbose_name='Estado'),
        ),
    ]
