# Generated by Django 5.2.1 on 2025-05-23 15:23

import gestion_propiedad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0006_alter_propiedade_estado_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedade',
            name='fpm',
            field=models.IntegerField(blank=True, null=True, validators=[gestion_propiedad.models.validar_positivo], verbose_name='Fondo Puesta en Marcha'),
        ),
    ]
