# Generated by Django 5.2.1 on 2025-05-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0007_propiedade_fpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedade',
            name='torre',
            field=models.ForeignKey(default=1, help_text='Nombre del Torre', on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.torre', verbose_name='Torre'),
            preserve_default=False,
        ),
    ]
