# Generated by Django 5.2.1 on 2025-05-26 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empresa', '0001_initial'),
        ('gestion_propiedad', '0008_propiedade_torre'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='empresa_vende',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_empresa.empresa', verbose_name='Empresa'),
        ),
    ]
