# Generated by Django 5.2.1 on 2025-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0009_condominio_empresa_vende'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedade',
            name='rol_bodega',
            field=models.CharField(default='1234-1234', help_text='Rol Bodega', max_length=50, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='rol_estacionamiento',
            field=models.CharField(default='5252-8585', help_text='Rol Estacionamiento', max_length=50, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='valor_bodega',
            field=models.CharField(default=150, help_text='Valor Bodega', max_length=50, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedade',
            name='valor_estacionamiento',
            field=models.IntegerField(default=0, help_text='Valor Estacionamiento', verbose_name='Valor'),
        ),
    ]
