# Generated by Django 5.2.1 on 2025-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0010_propiedade_rol_bodega_propiedade_rol_estacionamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedade',
            name='valor_bodega',
            field=models.FloatField(help_text='Valor Bodega', verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='propiedade',
            name='valor_estacionamiento',
            field=models.FloatField(default=0, help_text='Valor Estacionamiento', verbose_name='Valor'),
        ),
    ]
