# Generated by Django 5.2.1 on 2026-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_propiedad', '0011_alter_propiedade_valor_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedade',
            name='ori_propiedad',
            field=models.CharField(choices=[('NORTE', 'NORTE'), ('SUR', 'SUR'), ('ORIENTE', 'ORIENTE'), ('PONIENTE', 'PONIENTE'), ('NOR ORIENTE', 'NOR ORIENTE'), ('SUR PONIENTE', 'SUR PONIENTE'), ('NOR PONIENTE', 'NOR PONIENTE'), ('SUR ORIENTE', 'SUR ORIENTE')], default='NORTE', help_text='Orientación Depto', max_length=30, verbose_name='Orientación'),
        ),
    ]
