# Generated by Django 5.2.1 on 2025-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modelo Vacio',
                'verbose_name_plural': 'Modelos Vacios',
                'db_table': 'modelo_vacio',
            },
        ),
    ]
