# Generated by Django 5.2.1 on 2025-05-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_propiedad', '0005_alter_propiedade_valor_cchc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoPostVenta',
            fields=[
                ('id_requerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha ingreso')),
                ('solicitud_cliente', models.TextField(verbose_name='Solicitud del cliente')),
                ('recinto', models.CharField(max_length=50, verbose_name='Recinto')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar')),
                ('item', models.CharField(max_length=50, verbose_name='Ítem')),
                ('problema', models.TextField(verbose_name='Descripción del problema')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('estado', models.CharField(default='Pendiente', max_length=30, verbose_name='Estado')),
                ('causa', models.CharField(max_length=100, verbose_name='Causa')),
                ('alcance_responsabilidad', models.CharField(max_length=100, verbose_name='Alcance de responsabilidad')),
                ('mo', models.FloatField(default=0, help_text='Costo Mano de Obra', verbose_name='MO')),
                ('materiales', models.FloatField(default=0, verbose_name='Materiales')),
                ('subcontrato', models.FloatField(default=0, verbose_name='Subcontrato')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario adicional')),
                ('propiedad', models.ForeignKey(help_text='Solo propiedades entregadas', limit_choices_to={'estado_propiedad': 'Entregado'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.propiedade', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Requerimiento de Postventa',
                'verbose_name_plural': 'Requerimientos de Postventa',
                'db_table': 'requerimientos_postventa',
                'ordering': ['-fecha'],
            },
        ),
    ]
