# Generated by Django 5.2.1 on 2025-05-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_postventa', '0001_initial'),
        ('gestion_propiedad', '0006_alter_propiedade_estado_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcanceResponsabilidad',
            fields=[
                ('id_alcanceresponsabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id_causa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id_problema', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id_recinto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='requerimientopostventa',
            name='id_requerimiento',
        ),
        migrations.AddField(
            model_name='requerimientopostventa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='materiales',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='mo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='propiedad',
            field=models.ForeignKey(limit_choices_to={'estado_propiedad': 'Entregado'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.propiedade'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='subcontrato',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='alcance_responsabilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.alcanceresponsabilidad'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='causa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.causa'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.especialidad'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.item'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.lugar'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='problema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.problema'),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='recinto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_postventa.recinto'),
        ),
    ]
