# Generated by Django 5.2.1 on 2025-05-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_postventa', '0002_alcanceresponsabilidad_causa_especialidad_item_lugar_and_more'),
        ('gestion_propiedad', '0006_alter_propiedade_estado_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='estado',
            field=models.CharField(choices=[('Resuelto', 'Resuelto'), ('Trabajos', 'Trabajos'), ('Visita', 'Visita'), ('Cerrado', 'Cerrado'), ('Pendiente', 'Pendiente'), ('No Aplica', 'No Aplica'), ('Pospuesto', 'Pospuesto'), ('Propietario rechaza trabajos ', 'Propietario rechaza trabajos '), ('Observación', 'Observación'), ('Observación Entrega', 'Observación Entrega'), ('Terminado', 'Terminado')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='requerimientopostventa',
            name='propiedad',
            field=models.ForeignKey(limit_choices_to={'estado_propiedad': 'Entregada'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_propiedad.propiedade'),
        ),
    ]
