"""
Django settings for OPMS project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
# from OPMS.jazzmin_settings import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS
from OPMS.database import *
from OPMS.unfold_settings import UNFOLD
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(BASE_DIR / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f-(5pmjk#d8#*bytl*0c$6ta1pit(!rff8(qhjk0g64p)k)=z$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'unfold',
    'unfold.contrib.import_export',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion_clientes',
    'gestion_contable',
    'gestion_propiedad',
    'gestion_recuperacion',
    'gestion_escrituracion',
    'gestion_postventa',
    'gestion_empresa',
    'rest_framework',
    'drf_spectacular',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Internacionalización / idioma
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OPMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OPMS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

DATABASES = {
    # 'default': DATABASES_POSTGRESQL_DEMO_1
    # 'default':DATABASES_POSTGRESQL_DEMO_2
    'default': DATABASES_SQLITE
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

LANGUAGE_CODE = "es-cl"
TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Puedes cambiar 'staticfiles' por el nombre que prefieras

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
BCCH_API_TOKEN = os.getenv("BCCH_API_TOKEN")
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Variables de JAZZMIN desde jazzmin_settings.py
# JAZZMIN_SETTINGS = JAZZMIN_SETTINGS
# JAZZMIN_UI_TWEAKS = JAZZMIN_UI_TWEAKS

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',  # Si usas tokens
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Permitir solo usuarios autenticados
    ],

}

""" 
Ver la documentación:
https://drf-spectacular.readthedocs.io/en/latest/settings.html
"""
SPECTACULAR_SETTINGS = {
    'TITLE': 'SARAMS API',
    'DESCRIPTION': 'Api para SARAMS ',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    "CONTACT": {"name": "Soporte", "email": "soporte@miempresa.com"},
    "LICENSE": {"name": "MIT", "url": "https://opensource.org/licenses/MIT"},
    'ENUM_NAME_OVERRIDES': {
        'EstadoModeloEnum': 'EstadoModeloEnum',
        'TipoVentaEnum': 'TipoVentaEnum',
    },
    # OTHER SETTINGS
}

# ==========================================
# AUTENTICACIÓN
# ==========================================

LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/admin/"


# ==========================================
# EMAIL - DESARROLLO
# ==========================================

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = "SARAMS <no-reply@localhost>"